// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManager.Infrastructure;

#nullable disable

namespace StudentManager.Infrastructure.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20260803191859_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("StudentManager.Domain.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64);


                    b.Property<bool>("EnrolmentCompleted");


                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);


                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
